// Autogenerated from Pigeon (v16.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by QLQuickLookApi.
NSObject<FlutterMessageCodec> *QLQuickLookApiGetCodec(void);

@protocol QLQuickLookApi
/// Opens file saved at [url] in iOS QuickLook
///
/// The file should be saved at the ApplicationDocumentsDirectory (check out the example at https://pub.dev/packages/quick_look/example)
- (void)openURLUrl:(NSString *)url completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
/// Opens files saved at [resourceURLs] in iOS QuickLook (user can swipe between them)
///
/// Sets the current item in view to [initialIndex]
///
/// The files should be saved at the ApplicationDocumentsDirectory (check out the example at https://pub.dev/packages/quick_look/example)
- (void)openURLsResourceURLs:(NSArray<NSString *> *)resourceURLs initialIndex:(NSInteger)initialIndex completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
/// Returns whether iOS QuickLook supports the saved at [url] file type (and can preview it) or not
///
/// The list of supported file types varies depending on iOS version
- (void)canOpenURLUrl:(NSString *)url completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpQLQuickLookApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<QLQuickLookApi> *_Nullable api);

NS_ASSUME_NONNULL_END
