// Autogenerated from Pigeon (v25.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *QLGetMessagesCodec(void);

@protocol QLQuickLookApi
/// Opens file saved at [url] in iOS QuickLook
///
/// (iOS 13+) [isDismissable] configures whether QuickLook is dismissable
/// by a swipe from top to bottom
///
/// The file should be saved at the ApplicationDocumentsDirectory (check out the example at https://pub.dev/packages/quick_look/example)
- (void)openURLUrl:(NSString *)url isDismissable:(BOOL)isDismissable completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
/// Opens files saved at [resourceURLs] in iOS QuickLook
/// (user can swipe between them)
///
/// Sets the current item in view to [initialIndex]
/// (iOS 13+) [isDismissable] configures whether QuickLook is dismissable
/// by a swipe from top to bottom
///
/// The files should be saved at the ApplicationDocumentsDirectory (check out the example at https://pub.dev/packages/quick_look/example)
- (void)openURLsResourceURLs:(NSArray<NSString *> *)resourceURLs initialIndex:(NSInteger)initialIndex isDismissable:(BOOL)isDismissable completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
/// Returns whether iOS QuickLook supports the saved at [url] file type (and can preview it) or not
///
/// The list of supported file types varies depending on iOS version
- (void)canOpenURLUrl:(NSString *)url completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpQLQuickLookApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<QLQuickLookApi> *_Nullable api);

extern void SetUpQLQuickLookApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<QLQuickLookApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
