// Autogenerated from Pigeon (v29.0.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class MessagesPigeonCodecReader: FlutterStandardReader {
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol QuickLookApi {
  /// Opens file saved at [url] in iOS QuickLook
  ///
  /// (iOS 13+) [isDismissable] configures whether QuickLook is dismissable
  /// by a swipe from top to bottom
  ///
  /// Pass an absolute local file path, not a URL string.
  func openURL(url: String, isDismissable: Bool) async throws -> Bool
  /// Opens files saved at [resourceURLs] in iOS QuickLook
  /// (user can swipe between them)
  ///
  /// Sets the current item in view to [initialIndex]
  /// (iOS 13+) [isDismissable] configures whether QuickLook is dismissable
  /// by a swipe from top to bottom
  ///
  /// Pass absolute local file paths, not URL strings.
  func openURLs(resourceURLs: [String], initialIndex: Int64, isDismissable: Bool) async throws -> Bool
  /// Returns whether iOS QuickLook
  /// supports the saved at [url] file type (and can preview it) or not
  ///
  /// The list of supported file types varies depending on iOS version
  func canOpenURL(url: String) async throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class QuickLookApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `QuickLookApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: QuickLookApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Opens file saved at [url] in iOS QuickLook
    ///
    /// (iOS 13+) [isDismissable] configures whether QuickLook is dismissable
    /// by a swipe from top to bottom
    ///
    /// Pass an absolute local file path, not a URL string.
    let openURLChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.quick_look.QuickLookApi.openURL\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openURLChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let isDismissableArg = args[1] as! Bool
        Task { @MainActor in
          do {
            let result = try await api.openURL(url: urlArg, isDismissable: isDismissableArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      openURLChannel.setMessageHandler(nil)
    }
    /// Opens files saved at [resourceURLs] in iOS QuickLook
    /// (user can swipe between them)
    ///
    /// Sets the current item in view to [initialIndex]
    /// (iOS 13+) [isDismissable] configures whether QuickLook is dismissable
    /// by a swipe from top to bottom
    ///
    /// Pass absolute local file paths, not URL strings.
    let openURLsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.quick_look.QuickLookApi.openURLs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openURLsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let resourceURLsArg = args[0] as! [String]
        let initialIndexArg = args[1] as! Int64
        let isDismissableArg = args[2] as! Bool
        Task { @MainActor in
          do {
            let result = try await api.openURLs(resourceURLs: resourceURLsArg, initialIndex: initialIndexArg, isDismissable: isDismissableArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      openURLsChannel.setMessageHandler(nil)
    }
    /// Returns whether iOS QuickLook
    /// supports the saved at [url] file type (and can preview it) or not
    ///
    /// The list of supported file types varies depending on iOS version
    let canOpenURLChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.quick_look.QuickLookApi.canOpenURL\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      canOpenURLChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.canOpenURL(url: urlArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      canOpenURLChannel.setMessageHandler(nil)
    }
  }
}
